version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: library-system-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha01
      MYSQL_DATABASE: library-systemDB
    ports:
      - "3308:3306"
    cap_add:
      - SYS_NICE